version: "3.1"
services:
    php-fpm:
      build: ../phpdocker/php-fpm
      container_name: test-data-php-fpm
      working_dir: /application
      volumes:
        - ../../:/application
        - ../phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ../../.composer:/.composer
      environment:
        LOCAL_USER_ID: ${USER_ID}
        LOCAL_GROUP_ID: ${GROUP_ID}
      tty: true
      stdin_open: true

    mongo:
      image: mongo:3.6
      container_name: test-data-mongo
      ports:
        - "27018:27017"
      volumes:
        - ./_data:/data/db
      user: ${USER_ID}
